# Copyright 2023 Salesforce, Inc. All rights reserved.
[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    ".idea"
]

[placeholders.useconfig]
type    = "bool"
prompt  = "Does your policy need external configuration? (true/false)"
default = true

[placeholders.description]
type    = "string"
prompt  = "Provide a description of the project"
default = "Project description"


ignore = [
    ".devcontainer/",
    ".vscode/launch.json",
    ".vscode/tasks.json",
    "docs/",
    "scripts/",
    ".dockerignore",
    ".gitpod.Dockerfile",
    ".gitpod.yml",
]

[hooks]
init = ["init-script.rhai"]
post = ["post-script.rhai"]
