# Copyright 2023 Salesforce, Inc. All rights reserved.
---
# This descriptor is used in local mode to describe how shape of configuration of the policy needs to be.
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  name: {{ project-name }}
spec:
  extends:
    - name: extension-definition
    - name: envoy-filter
    - name: proxy-wasm-filter
  properties:
    {% if useconfig -%}
    headerName:
      type: string
    expectedHeaders:
      type: number
      default: 1
    {% endif -%}
   #Required fields for wasm based policies
    rootId:
      type: string
      default: main
    implementation:
      type: string
      default: base64://<ENCODED>
  {% if useconfig -%}
  required:
    - headerName
    - expectedHeaders
{% endif -%}
